### PR TITLE
added \\ where needed in description

### PR DESCRIPTION
**Pull request by Sharonpik**
The sdk creation is failing due to the spec having "...\\\\`access_token\\\\`. Caso a API Key seja inválida ou não seja informada, o Asaas retornará \`HTTP 401\`...." in the description.
We can deal with a cases of just "\`"  or  "\\\\\`", but we can't deal with a mix of "\\\\\`" and "`" in the same line.
Manually changed for now.

### CODE REVIEW

**Comment by sagivo** [comment]
Curious how should we automate this fix moving forward

**Comment by Sharonpik** [comment]
My suggestion for the future is two steps: 
1. remove all \ that are used for escaping
2. find all ` and replace them with \\`

**Review by sagivo — APPROVED** [review]
Let's add a todo or a fast follow to automate this fix

**Comment by Sharonpik** [comment]
Opening an issue and adding a TODO in the postman transform controller

**Pull request merged**
